replicaCount: 4

image:
  repository: nirmaldocker1987/java-maven-project-dev
  tag: "8"
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  targetPort: 8080

containerPort: 8080

resources: {}
